# Generated by Django 3.2.10 on 2022-01-30 05:54

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', person.models.UnsignedTinyIntField()),
                ('etc', models.CharField(default=None, max_length=100)),
                ('create_at', models.TimeField(auto_created=True)),
                ('update_at', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
