# Generated by Django 3.2.10 on 2022-01-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='etc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
