# Generated by Django 3.2.10 on 2022-01-30 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
