# Generated by Django 3.2.10 on 2022-01-30 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
