# Generated by Django 3.2.10 on 2022-01-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20220130_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateField(auto_created=True, db_index=True),
        ),
    ]
