# Generated by Django 3.2.10 on 2022-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20220201_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'watch',
            },
        ),
    ]
